name: CI Smoke Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Set up environment file
        run: |
          cp .env.example .env
          echo "PORT=3000" >> .env
          echo "MONGO_URI=mongodb://root:example@mongo:27017/market_data?authSource=admin" >> .env
          echo "SECRET_REFRESH_TOKEN=test-token" >> .env

      - name: Build and start services
        run: docker-compose up -d --build

      - name: Wait for services to be healthy
        run: |
          echo "Waiting for API to be ready..."
          for i in {1..30}; do
            if curl -s http://localhost:3000/health | grep -q "OK"; then
              echo "API is up!"
              exit 0
            fi
            echo "Attempt $i/30 failed, waiting..."
            sleep 2
          done
          echo "API failed to start"
          exit 1

      - name: Install dependencies
        run: npm install

      - name: Run smoke tests
        run: node smoke-test.js
        env:
          SECRET_REFRESH_TOKEN: test-token